[build]
  environment = { SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_PROJECT_ID,VITE_SUPABASE_PUBLISHABLE_KEY,VITE_SUPABASE_URL,VITE_GOOGLE_MAPS_API_KEY" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200