// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brxssrnrapzlgyfsdmbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyeHNzcm5yYXB6bGd5ZnNkbWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5MjY0MTgsImV4cCI6MjA4NDUwMjQxOH0.mCitzzfQApUi8jQkFQ82ERLxmrdoR2p6FAg5TWH2fP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});